[workspace.metadata.crane]
name = "Tree-Sitter MCP Server"
version = "0.0.1"

[workspace.package]
version = "0.0.1"
authors = ["Darshan Kumawat <mail@darshan.qzz.io>"]
edition = "2024"
categories = ["mcp", "tree-sitter"]

[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.dependencies]
anyhow = "1.0"
rmcp = { version = "2.2", features = ["schemars"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio = { version = "1.0", features = ["full"] }
rstest = "0.26"
tempfile = "3"
insta = { version = "1.0", features = ["json", "glob"] }
criterion = { version = "0.8", features = ["html_reports"] }

### Local Crates

config = { path = "crates/config" }
grammar = { path = "crates/grammar" }
mcp = { path = "crates/mcp" }

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
