[extensions]
rust = ["rs"]
sway = ["sw"]
toml = [
  "toml",
  { glob = "pdm.lock" },
  { glob = "poetry.lock" },
  { glob = "Cargo.lock" },
  { glob = "uv.lock" },
  { glob = "containers.conf" },
  { glob = "containers.conf.d/*.conf" },
  { glob = "containers.conf.modules/*.conf" },
  { glob = "mounts.conf" },
  { glob = "policy.conf" },
  { glob = "registries.conf" },
  { glob = "storage.conf" },
]
awk = ["awk", "gawk", "nawk", "mawk"]
protobuf = ["proto"]
textproto = ["txtpb", "textpb", "textproto"]
eiffel = ["e"]
elixir = ["ex", "exs", { glob = "mix.lock" }]
fennel = ["fnl", "fnlm"]
fish = ["fish"]
flatbuffers = ["fbs"]
mint = ["mint"]
mojo = ["mojo", "🔥"]
janet = ["cgen", "janet", "jdn"]
json = [
  "json",
  "arb",
  "ipynb",
  "geojson",
  "gltf",
  "webmanifest",
  { glob = "flake.lock" },
  { glob = ".babelrc" },
  { glob = ".bowerrc" },
  { glob = ".jscrc" },
  "js.map",
  "ts.map",
  "css.map",
  { glob = ".jslintrc" },
  "jsonl",
  { glob = ".vuerc" },
  { glob = "composer.lock" },
  { glob = ".watchmanconfig" },
  "avsc",
  "ldtk",
  "ldtkl",
  { glob = ".swift-format" },
  "sublime-build",
  "sublime-color-scheme",
  "sublime-commands",
  "sublime-completions",
  "sublime-keymap",
  "sublime-macro",
  "sublime-menu",
  "sublime-mousemap",
  "sublime-project",
  "sublime-settings",
  "sublime-theme",
  "sublime-workspace",
  "code-workspace",
  { glob = ".pytest_cache/v/cache/*" }, # https://docs.pytest.org/en/latest/reference/reference.html#confval-cache_dir
  { glob = "devenv.lock" },             # https://devenv.sh/
  { glob = "devbox.lock" },             # https://www.jetify.com/docs/devbox/
  { glob = "manifest.lock" },           # https://flox.dev/docs/
  { glob = "deno.lock" },               # https://deno.com/
]
jsonc = [
  "jsonc",
  { glob = "{t,j}sconfig.json" },
  { glob = "bun.lock" },
  { glob = ".devcontainer.json" },
  { glob = "devcontainer.json" },
  { glob = ".vscode/*.json" },
]
json-ld = ["jsonld"]
json5 = ["json5"]
c = ["c"]
cpp = [
  "cc",
  "hh",
  "c++",
  "cpp",
  "hpp",
  "h",
  "ipp",
  "tpp",
  "cxx",
  "hxx",
  "ixx",
  "txx",
  "ino",
  "C",
  "H",
  "cu",
  "cuh",
  "cppm",
  "h++",
  "ii",
  "inl",
  { glob = ".hpp.in" },
  { glob = ".h.in" },
]
crystal = ["cr"]
c-sharp = ["cs", "csx", "cake"]
c3 = ["c3", "c3i", "c3t"]
cel = ["cel"]
spicedb = ["zed"]
go = ["go"]
gomod = [{ glob = "go.mod" }]
gotmpl = ["gotmpl"]
gowork = [{ glob = "go.work" }]
javascript = [
  "js",
  "mjs",
  "cjs",
  "rules",
  "es6",
  "pac",
  "gs",
  { glob = ".node_repl_history" },
  { glob = "jakefile" },
]

jsx = ["jsx"]
typescript = ["ts", "mts", "cts"]
typespec = ["tsp"]
tsx = ["tsx"]
css = ["css"]
scss = ["scss"]
less = ["less"]
html = [
  "html",
  "htm",
  "shtml",
  "xhtml",
  "xht",
  "jsp",
  "asp",
  "aspx",
  "jshtm",
  "volt",
  "rhtml",
  "cshtml",
]
python = [
  "py",
  "pyi",
  "py3",
  "pyw",
  "ptl",
  "rpy",
  "cpy",
  "ipy",
  "pyt",
  { glob = ".python_history" },
  { glob = ".pythonstartup" },
  { glob = ".pythonrc" },
  { glob = "*SConstruct" },
  { glob = "*SConscript" },
  { glob = "*sconstruct" },
]
nickel = ["ncl"]
nix = ["nix"]
ruby = [
  "rb",
  "rake",
  "irb",
  "gemspec",
  "rabl",
  "jbuilder",
  "jb",
  "podspec",
  "rjs",
  "rbi",
  "rbs",
  { glob = "rakefile" },
  { glob = "gemfile" },
  { glob = "Rakefile" },
  { glob = "Gemfile" },
  { glob = "Podfile" },
  { glob = "Vagrantfile" },
  { glob = "Brewfile" },
  { glob = "*.Brewfile" },
  { glob = "Guardfile" },
  { glob = "Capfile" },
  { glob = "Cheffile" },
  { glob = "Hobofile" },
  { glob = "Appraisals" },
  { glob = "Rantfile" },
  { glob = "Berksfile" },
  { glob = "Berksfile.lock" },
  { glob = "Thorfile" },
  { glob = "Puppetfile" },
  { glob = "Fastfile" },
  { glob = "Appfile" },
  { glob = "Deliverfile" },
  { glob = "Matchfile" },
  { glob = "Scanfile" },
  { glob = "Snapfile" },
  { glob = "Gymfile" },
  { glob = ".irbrc" },
]
rshtml = [{ glob = "*.rs.html" }]
bash = [
  "sh",
  "bash",
  "ash",
  "dash",
  "ksh",
  "mksh",
  "zsh",
  "zshenv",
  "zlogin",
  "zlogout",
  "zprofile",
  "zshrc",
  "eclass",
  "ebuild",
  "bazelrc",
  "Renviron",
  "zsh-theme",
  "cshrc",
  "tcshrc",
  "bashrc_Apple_Terminal",
  "zshrc_Apple_Terminal",
  { glob = "i3/config" },
  { glob = "sway/config" },
  { glob = ".tmux.conf" },
  { glob = "tmux.conf" },
  { glob = ".sh_history" },
  { glob = ".bash_history" },
  { glob = ".bash_login" },
  { glob = ".bash_logout" },
  { glob = ".bash_profile" },
  { glob = ".bashrc" },
  { glob = ".profile" },
  { glob = ".zshenv" },
  { glob = ".zlogin" },
  { glob = ".zlogout" },
  { glob = ".zprofile" },
  { glob = ".zshrc" },
  { glob = ".zimrc" },
  { glob = "APKBUILD" },
  { glob = ".bash_aliases" },
  { glob = "bash_completion" },
  { glob = "bash-completion/completions/*" },
  { glob = "bash_completion.d/*" },
  { glob = ".Renviron" },
  { glob = ".xprofile" },
  { glob = ".xsession" },
  { glob = ".xsessionrc" },
  { glob = ".yashrc" },
  { glob = ".yash_profile" },
  { glob = ".hushlogin" },
  { glob = ".xinitrc" },                      # ~/.xinitrc
  { glob = "xinitrc" },                       # /etc/X11/xinit/xinitrc
  { glob = ".xserverrc" },                    # ~/.xserverrc
  { glob = "xserverrc" },                     # /etc/X11/xinit/xserverrc
  { glob = "direnvrc" },                      # ~/.config/direnv/direnvrc
]
php = ["php", "inc", "php4", "php5", "phtml", "ctp"]
blade = [{ glob = "*.blade.php" }, "blade"]
twig = ["twig"]
latex = ["tex", "sty", "cls", "Rd", "bbx", "cbx"]
bibtex = ["bib"]
lean = ["lean"]
lpf = ["lpf"]
julia = ["jl"]
java = ["java", "jav", "pde"]
smali = ["smali"]
ledger = ["ldg", "ledger", "journal"]
beancount = ["beancount", "bean"]
ocaml = ["ml"]
ocaml-interface = ["mli"]
dune = [{ glob = "dune-project" }, { glob = "dune" }]
lua = ["lua", "rockspec"]
teal = ["tl"]
svelte = ["svelte"]
vue = ["vue"]
yaml = [
  "yml",
  "yaml",
  { glob = ".prettierrc" },
  { glob = ".clangd" },
  { glob = ".clang-format" },
  { glob = ".clang-tidy" },
  { glob = ".gem/credentials" },
  { glob = ".kube/config" },
  { glob = ".kube/kuberc" },
  { glob = "yarn.lock" },
  "sublime-syntax",
  "bu",
  { glob = ".stylelintrc" },     # https://stylelint.io/user-guide/configure/
  { glob = ".puppeteerrc" },     # https://pptr.dev/guides/configuration
]
nestedtext = ["nt"]
haskell = ["hs", "hs-boot", "hsc"]
haskell-persistent = ["persistentmodels"]
haskell-literate = ["lhs"]
purescript = ["purs"]
zig = ["zig", "zon"]
picat = ["pi", "picat"]
prolog = ["pl", "prolog"]
tsq = [
  { glob = "queries/*.scm" },
  { glob = "injections.scm" },
  { glob = "highlights.scm" },
  { glob = "indents.scm" },
  { glob = "textobjects.scm" },
  { glob = "locals.scm" },
  { glob = "tags.scm" },
]
cmake = ["cmake", { glob = "CMakeLists.txt" }]
make = [
  { glob = "Makefile" },
  { glob = "makefile" },
  "make",
  "mk",
  "mak",
  { glob = "GNUmakefile" },
  { glob = "OCamlMakefile" },
]
glsl = ["glsl", "vert", "tesc", "tese", "geom", "frag", "comp"]
penrose = ["substance", "style", "domain"]
perl = [
  "pl",
  "pm",
  "t",
  "psgi",
  "raku",
  "rakumod",
  "rakutest",
  "rakudoc",
  "nqp",
  "p6",
  "pl6",
  "pm6",
  { glob = "latexmkrc" },
  { glob = ".latexmkrc" },
]
embedded-perl = ["ep", { glob = "*.html.ep" }]
pod = ["pod"]
racket = ["rkt", "rktd", "rktl", "scrbl", "zuo"]
common-lisp = ["lisp", "asd", "cl", "l", "lsp", "ny", "podsl", "ros", "sexp"]
wesl = ["wesl"]
wgsl = ["wgsl"]
llvm = ["ll"]
llvm-mir-yaml = ["mir"]
tablegen = ["td"]
mail = ["eml"]
markdown = [
  "md",
  "livemd",
  "markdown",
  "mdx",
  "mkd",
  "mkdn",
  "mdwn",
  "mdown",
  "markdn",
  "mdtxt",
  "mdtext",
  "workbook",
  { glob = "PULLREQ_EDITMSG" },
]
djot = ["dj", "djot"]
dart = ["dart"]
scala = ["scala", "sbt", "sc"]
dockerfile = [
  "Dockerfile",
  { glob = "Dockerfile" },
  { glob = "Dockerfile.*" },
  "dockerfile",
  { glob = "dockerfile" },
  { glob = "dockerfile.*" },
  "Containerfile",
  { glob = "Containerfile" },
  { glob = "Containerfile.*" },
  "containerfile",
  { glob = "containerfile" },
  { glob = "containerfile.*" },
]
docker-compose = [
  { glob = "docker-compose.yaml" },
  { glob = "docker-compose.yml" },
  { glob = "compose.yaml" },
  { glob = "compose.yml" },
]
git-commit = [
  { glob = "COMMIT_EDITMSG" },
  { glob = "MERGE_MSG" },
  { glob = "TAG_EDITMSG" },
]
git-notes = [{ glob = "NOTES_EDITMSG" }, { glob = "EDIT_DESCRIPTION" }]
github-action = [
  { glob = ".github/workflows/*.yaml" },
  { glob = ".github/workflows/*.yml" },
]
diff = ["diff", "patch", "rej"]
git-rebase = [{ glob = "git-rebase-todo" }]
regex = ["regex", { glob = ".Rbuildignore" }]
git-config = [
  "gitconfig",
  { glob = ".gitmodules" },
  { glob = "gitconfig" },
  { glob = ".gitconfig" },
  { glob = ".git/config" },
  { glob = ".config/git/config" },
  { glob = ".git/modules/*/config" },
  { glob = "config.worktree" },
]
git-attributes = [
  { glob = ".gitattributes" },
  { glob = ".config/git/attributes" },
]
git-ignore = [
  { glob = ".gitignore_global" },
  { glob = "git/ignore" },
  { glob = ".git/info/exclude" },
  { glob = ".ignore" },
  { glob = "CODEOWNERS" },
  { glob = ".config/helix/ignore" },
  { glob = ".helix/ignore" },
  { glob = ".*ignore" },
  { glob = ".git-blame-ignore-revs" },
]
graphql = ["gql", "graphql", "graphqls"]
elm = ["elm"]
iex = ["iex"]
rescript = ["res"]
erlang = [
  "erl",
  "hrl",
  "app",
  { glob = "rebar.config" },
  { glob = "rebar.lock" },
  { glob = "*.app.src" },
]
kotlin = ["kt", "kts"]
hcl = ["hcl", "tf", "nomad"]
tfvars = ["tfvars"]
org = ["org"]
solidity = ["sol"]
gleam = ["gleam"]
quarto = ["qmd"]
ron = ["ron"]
robot = ["robot", "resource"]
r = [
  "r",
  "R",
  { glob = ".Rprofile" },
  { glob = "Rprofile.site" },
  { glob = ".RHistory" },
]
rmarkdown = ["rmd", "Rmd"]
swift = ["swift", "swiftinterface"]
erb = ["erb"]
ejs = ["ejs"]
eex = ["eex"]
heex = ["heex"]
sql = ["sql", "dsql"]
gdscript = ["gd"]
godot-resource = ["tscn", "tres", "godot", "gdextension"]
nu = ["nu", "nuon"]
vala = ["vala", "vapi"]
hare = ["ha"]
devicetree = ["dts", "dtsi"]
cairo = ["cairo"]
cpon = ["cpon", "cp"]
odin = ["odin"]
meson = [
  { glob = "meson.build" },
  { glob = "meson.options" },
  { glob = "meson_options.txt" },
]
sshclientconfig = [
  { glob = ".ssh/config" },
  { glob = "/etc/ssh/ssh_config" },
  { glob = "ssh_config.d/*.conf" },
]
scheme = ["ss", "scm", "sld"]
v = ["v", "vv", "vsh"]
verilog = ["v", "vh"]
systemverilog = ["sv", "svh"]
edoc = ["edoc", "edoc.in"]
jsdoc = ["jsdoc"]
openscad = ["scad"]
prisma = ["prisma"]
clojure = ["clj", "cljs", "cljc", "clje", "cljr", "cljx", "edn", "boot"]
starlark = [
  "bzl",
  "bazel",
  "star",
  { glob = "BUILD" },
  { glob = "BUCK" },
  { glob = "BUILD.*" },
  { glob = "WORKSPACE" },
  { glob = "WORKSPACE.bzlmod" },
  { glob = "PACKAGE" },
]
elvish = ["elv"]
idris = ["idr"]
fortran = ["f", "for", "f90", "f95", "f03", "F", "F90", "F95", "F03"]
ungrammar = ["ungram", "ungrammar"]
dot = ["dot"]
cue = ["cue"]
slang = ["slang"]
slint = ["slint"]
task = ["task"]
xit = ["xit"]
esdl = ["gel", "esdl"]
pascal = ["pas", "pp", "inc", "lpr", "lfm"]
sml = ["sml"]
jsonnet = ["libsonnet", "jsonnet"]
ada = ["adb", "ads"]
astro = ["astro"]
bass = ["bass"]
wat = ["wat"]
wast = ["wast"]
d = ["d", "dd"]
vhs = ["tape"]
kdl = ["kdl"]
xml = [
  "ascx",
  "atom",
  "axaml",
  "axml",
  "bpmn",
  "checkstyle",
  "cpt",
  "csl",
  "csproj.user",
  "dita",
  "ditamap",
  "dtml",
  "fods",
  "fodt",
  "fxml",
  "gir",
  "glif",
  "gml",
  "gpx",
  "iml",
  "isml",
  "itermcolors",
  "jmx",
  "kml",
  "launch",
  "menu",
  "mobileconfig",
  "mpd",
  "musicxml",
  "mxml",
  "ncx",
  "nuspec",
  "opml",
  "osc",
  "osm",
  "plist",
  "policy",
  "pt",
  "publishsettings",
  "pubxml",
  "pubxml.user",
  "rbxlx",
  "rbxmx",
  "resx",
  "rng",
  "rss",
  "shproj",
  "smil",
  "storyboard",
  "sublime-snippet",
  "svg",
  "terminal",
  "tld",
  "tmx",
  "ui",
  "vbproj.user",
  "vcxproj",
  "vcxproj.filters",
  "wixproj",
  "wsdl",
  "wxi",
  "wxs",
  "xaml",
  "xbl",
  "xib",
  "xlf",
  "xliff",
  "xml",
  "xmp",
  "xoml",
  "xpdl",
  "xrc",
  "xsd",
  "xsl",
  "xul",
  { glob = "*.tm[Ll]anguage" },
  { glob = "*.tm[Pp]references" },
  { glob = "*.tm[Tt]heme" },
]
dtd = ["dtd", "ent"]
wit = ["wit"]
env = [
  { glob = ".env" },
  { glob = ".env.*" },
  { glob = ".envrc" },
  { glob = ".envrc.*" },
  { glob = "_environment" },          # https://quarto.org/docs/projects/environment.html#environment-file
  { glob = "_environment-*" },        # https://quarto.org/docs/projects/environment.html#profile-environments
  { glob = "_environment.local" },    # https://quarto.org/docs/projects/environment.html#local-environment
  { glob = "_environment.required" }, # https://quarto.org/docs/projects/environment.html#required-variables
  { glob = ".bazeliskrc" },           # https://github.com/bazelbuild/bazelisk#bazeliskrc-configuration-file
]
systemd = [
  # Systemd unit files
  "service",
  "automount",
  "device",
  "mount",
  "nspawn",
  "path",
  "scope",
  "slice",
  "socket",
  "swap",
  "target",
  "timer",
  { glob = "systemd/**/*.conf" },
]
ini = [
  "ini",
  "desktop",
  { glob = "mimeapps.list" },
  # Podman quadlets
  "container",
  "volume",
  "kube",
  "network",
  { glob = ".editorconfig" },
  { glob = ".npmrc" },
  { glob = "hgrc" },
  { glob = "npmrc" },
  { glob = "rclone.conf" },
  { glob = ".aws/config" },
  "properties",
  "cfg",
  "directory",
  { glob = ".wslconfig" },
]
inko = ["inko"]
bicep = ["bicep", "bicepparam"]
qml = ["qml"]
mermaid = ["mermaid", "mmd"]
matlab = ["m"]
ponylang = ["pony"]
dhall = ["dhall"]
sage = ["sage"]
msbuild = ["proj", "vbproj", "csproj", "fsproj", "targets", "props"]
pem = ["pem", "cert", "crt"]
passwd = [{ glob = "passwd" }]
hosts = [{ glob = "hosts" }]
uxntal = ["tal"]
yuck = ["yuck"]
prql = ["prql"]
po = ["po", "pot"]
nasm = ["asm", "S", "nasm"]
gas = ["s"]
rst = ["rst"]
capnp = ["capnp"]
smithy = ["smithy"]
hdl = ["hdl"]
vhdl = ["vhd", "vhdl"]
rego = ["rego"]
nim = ["nim", "nims", "nimble"]
cabal = ["cabal"]
hurl = ["hurl"]
markdoc = ["mdoc"]
opencl = ["cl"]
just = [
  "just",
  { glob = "justfile" },
  { glob = "Justfile" },
  { glob = ".justfile" },
  { glob = ".Justfile" },
]
gn = ["gn", "gni"]
blueprint = ["blp"]
forth = ["fs", "forth", "fth", "4th"]
fsharp = ["fs", "fsx", "fsi", "fsscript"]
t32 = ["cmm", "t32"]
webc = ["webc"]
typst = ["typst", "typ"]
nunjucks = ["njk"]
jinja = ["jinja", "jinja2", "j2"]
jjconfig = [
  { glob = "jj/config.toml" },
  { glob = "jj/**/*.toml" },
  { glob = ".jj/repo/*.toml" },
]
jjdescription = [{ glob = "*.jjdescription" }]
jjrevset = ["jjrevset"]
jjtemplate = ["jjtemplate"]
miseconfig = [
  { glob = "mise.toml" },
  { glob = ".mise.toml" },
  { glob = "mise.*.toml" },
  { glob = ".mise.*.toml" },
  { glob = "mise/config.toml" },
  { glob = ".mise/config.toml" },
  { glob = ".config/mise.toml" },
  { glob = ".config/mise/conf.d/*.toml" },
]
jq = ["jq"]
wren = ["wren"]
unison = ["u"]
todotxt = [{ glob = "*.todo.txt" }, "todotxt"]
strace = ["strace"]
gemini = ["gmi"]
agda = ["agda"]
templ = ["templ"]
dbml = ["dbml"]
bitbake = [
  "bb",
  "bbappend",
  "bbclass",
  { glob = "conf/*.conf" },
  { glob = "conf/*/*.{inc,conf}" },
  { glob = "recipe-*/*/*.inc" },
]
log = ["log"]
hoon = ["hoon"]
hocon = [
  { glob = "**/src/*/resources/**/*.conf" },
  { glob = "*scalafmt*.conf" },
  { glob = "*scalafix*.conf" },
]
koka = ["kk"]
tact = ["tact"]
pkl = ["pkl", "pcf", { glob = "PklProject" }]
groovy = [
  "groovy",
  "gradle",
  "jenkinsfile",
  { glob = "Jenkinsfile" },
  { glob = "Jenkinsfile.*" },
]
fidl = ["fidl"]
powershell = ["ps1", "psm1", "psd1", "pscc", "psrc"]
ld = ["ld"]
hy = ["hy"]
hyprlang = [{ glob = "hypr/*.conf" }]
tcl = ["tcl"]
supercollider = ["scd", "sc", "quark"]
rpmspec = ["spec"]
pkgbuild = [{ glob = "PKGBUILD" }]
helm = [
  { glob = "templates/*.yaml" },
  { glob = "templates/*.yml" },
  { glob = "templates/_*.tpl" },
  { glob = "templates/NOTES.txt" },
]
glimmer = [{ glob = "{app,addon}/{components,templates}/*.hbs" }]
ohm = ["ohm"]
earthfile = [{ glob = "Earthfile" }]
adl = ["adl"]
ldif = ["ldif"]
xtc = ["xtc", "xpc", "xoa"]
move = ["move"]
pest = ["pest"]
elisp = ["el"]
gjs = ["gjs"]
gts = ["gts"]
gherkin = ["feature"]
thrift = ["thrift"]
snakemake = ["smk", { glob = "Snakefile" }]
cylc = [{ glob = "suite.rc" }]
quint = ["qnt"]
spade = ["spd"]
amber = ["ab"]
koto = ["koto"]
gpr = ["gpr"]
vento = ["vto"]
nginx = [
  { glob = "sites-available/*.conf" },
  { glob = "sites-enabled/*.conf" },
  { glob = "nginx.conf" },
  { glob = "conf.d/*.conf" },
]
codeql = ["ql", "qll"]
gren = ["gren"]
ghostty = ["ghostty", { glob = "ghostty/config" }]
tera = ["tera"]
fga = ["fga"]
csv = ["csv"]
yara = ["yara", "yar"]
ink = ["ink"]
sourcepawn = ["sp", "inc"]
vim = ["vim", { glob = ".vimrc" }, { glob = ".nvimrc" }, { glob = ".exrc" }]
tlaplus = ["tla"]
werk = ["werk", { glob = "Werkfile" }]
debian = [
  "dsc",
  "changes",
  { glob = "debian/**/control" },
  { glob = "etc/apt/sources.list.d/*.sources" },
]
dunstrc = [{ glob = "dunst/dunstrc" }]
clarity = ["clar"]
alloy = ["als"]
luau = ["luau"]
caddyfile = [
  "Caddyfile",
  { glob = "Caddyfile" },
  { glob = "Caddyfile.*" },
  "caddyfile",
  { glob = "caddyfile" },
  { glob = "caddyfile.*" },
]
properties = ["properties", "prefs"]
robots = [{ glob = "robots.txt" }]
pip-requirements = [{ glob = "requirements.txt" }, { glob = "constraints.txt" }]
kconfig = ["Kconfig", { glob = "Kconfig.*" }]
doxyfile = [{ glob = "Doxyfile" }]
cross-config = [{ glob = "Cross.toml" }]
git-cliff-config = [{ glob = "cliff.toml" }]
cython = ["pxd", "pxi", "pyx"]
shellcheckrc = [{ glob = "shellcheckrc" }, { glob = ".shellcheckrc" }]
strictdoc = ["sdoc", "sgra"]
docker-bake = [
  { glob = "docker-bake.hcl" },
  { glob = "docker-bake.override.hcl" },
]
gitlab-ci = [{ glob = ".gitlab-ci.yml" }]
wikitext = ["wikimedia", "mediawiki", "wikitext"]
slisp = ["sl"]
nearley = ["ne"]
kcl = ["kcl"]
bovex = ["bovex", "bibvex"]
haxe = ["hx"]
basic = ["bas"]
freebasic = ["bas", "bi"]
scfg = ["scfg"]
ripple = [{ glob = "kanshi/config" }]
woodpecker-ci = [
  { glob = ".woodpecker.yaml" },
  { glob = ".woodpecker/*.yaml" },
  { glob = ".woodpecker/*.yml" },
]
chuck = [{ glob = "*.ck" }]
qmv = [{ glob = "/tmp/qmv*" }]
klog = ["klg"]
styx = ["styx"]
tilt = ["Tiltfile", "tiltfile"]
gnuplot = ["gnuplot", "plot", "plt"]
drools = ["drl"]
proverif = ["pv"]
ptx = ["ptx"]
tql = ["tql"]
