[package]
name = "grammar"
version = "0.0.1"
edition = "2024"

[dependencies]
tree-sitter = "0.26.11"
dlopen2 = { version = "0.9", default-features = false, features = ["symbor"] }
schemars = "1.2.2"
config.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
quickcheck = "1"
quickcheck_macros = "1"
serde_json.workspace = true
tree-sitter-rust = "0.24"
insta.workspace = true
criterion.workspace = true
rstest.workspace = true

[lib]
doctest = false

[[bench]]
name = "queries"
harness = false
